#!/bin/bash

# We need to create the resources first, that thave CRDs
terraform apply -target=helm_release.kube-prometheus-stack -target=helm_release.dapr-system

# Now we apply everything
terraform apply
