name: 'Backend Build and Deploy'

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  ci-servicea:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18' # The Go version to download (if necessary) and use.

      - name: Build go
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"'
        working-directory: servicea

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: servicea
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST }}/dkrizic/servicea:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.REGISTRY_HOST }}/dkrizic/servicea:latest

