fullnameOverride: number
image:
  repository: dkrizic/number
  tag: latest
  pullPolicy: Always
podAnnotations:
  dapr.io/enabled: "true"
  dapr.io/app-id: "number"
  dapr.io/app-port: "8000"
ingress:
  enabled: true
  hosts:
    - host: backend.minikube
      paths:
        - path: /number
          pathType: ImplementationSpecific
env:
  - name: STATE_STORE_NAME
    value: state
  - name: STATE_NAME
    value: orderNumber
